### ISSUE TITLE
I want to use this with electron webview

### ISSUE THREAD

**Issue by MXP2095onetechguy** [samuelmaddock/electron-browser-shell#11]
The chrome electron context menu needs webview support(if there is not one)

I have seen other alternative, but either those don't have webview support or they need electron that has higher version than what I use(I use 1.8.8), this module looks promising, so will you add webview support?
by the way, this is my [browser](https://github.com/MXP2095onetechguy/NodeJS-browser)

p.s. you can tell me if there is webview support and if that happens, tell me how to use it with webview and also, what is the minimum version does this module need

**Comment by samuelmaddock** [comment]
electron-chrome-context-menu requires Electron v9 at a minimum.
https://github.com/samuelmaddock/electron-browser-shell/blob/1b7e04ce41278a457d52f7952e650adb5b33e508/packages/electron-chrome-context-menu/package.json#L20

The [usage example](https://github.com/samuelmaddock/electron-browser-shell/tree/master/packages/electron-chrome-context-menu#usage) should work with webviews.

**Comment by MXP2095onetechguy** [comment]
ok
