### ISSUE TITLE
Extensions.addTab adds browser tab like UI which is visible on HTML DOM

### ISSUE THREAD

**Issue by Jenifer-TheCoder** [samuelmaddock/electron-browser-shell#27]
I have created sample Electron app and have added the below code to load and get extensions working!!

````
(async function main() {
  await app.whenReady()

  const browserWindow = new BrowserWindow()
  const ext = session.defaultSession.loadExtension('/Extension_path/')

  // Adds the active tab of the browser
  const extensions = new Extensions()
  extensions.addTab(browserWindow.webContents, browserWindow)
 // browserWindow.webContents.openDevTools({ mode: 'detach' })
  browserWindow.loadURL('https://google.com')
  browserWindow.show()
}())
````

- Could see expected chrome extension been loaded and working
- But on viewing the DOM data of the HTML, there is a browser tab kid of div is been added
- Can we get rid of this behavior to get chrome extension working as it is supposed in other browsers?
- Note:The chrome extension I am using is about capturing DOM properties,so it is important to capture as it is and not with extra div.

**Comment by samuelmaddock** [comment]
I'm having a difficult time understanding what you mean.

Calling extensions.addTab() does not create any UI elements in the DOM, it only observes the WebContents internally.

I suspect this issue is not related to electron-chrome-extensions, but rather the Election app you're modifying.

**Comment by Jenifer-TheCoder** [comment]
I really doubt sample electron app brings that tab UI behavior .
The sample app that I had created is via following the tutorial https://www.electronjs.org/docs/tutorial/quick-start .
The main file is just a simple file that creates browser window and load extension.
Let me bring the contents of the main.js file here:
```
const { app, session,BrowserWindow } = require('electron') 
const { Extensions } = require('electron-chrome-extensions')

// This method will be called when Electron has finished 
// initialization and is ready to create browser windows. 
// Some APIs can only be used after this event occurs. 
function createWindow () {
  const browserWindow = new BrowserWindow()
  const ext = session.defaultSession.loadExtension('<Path of Assima Train extension>')//You can download it from chrome-extensions
  const extensions = new Extensions()
  extensions.addTab(browserWindow.webContents, browserWindow)
  browserWindow.loadURL('https:\\google.com')
}

app.whenReady().then(createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
}) 
```

**Comment by samuelmaddock** [comment]
I still don't follow what the issue is. 

> But on viewing the DOM data of the HTML, there is a browser tab kid of div is been added

You need to post a screenshot of what you're seeing, but again, this package does not add anything to the DOM.

> Can we get rid of this behavior to get chrome extension working as it is supposed in other browsers?

You haven't described what the expected behavior is.

**Comment by Jenifer-TheCoder** [comment]
Attaching the snapshots:
Original application
![image](https://user-images.githubusercontent.com/43472476/118703407-af5eca80-b833-11eb-815f-d57dac0bbdb2.png)
Snapshot post the usage of above mentioned chrome extension which basically captures HTML as DOM:
![image](https://user-images.githubusercontent.com/43472476/118704832-26e12980-b835-11eb-88b2-3efbf9ea1e17.png)
- In the above snapshot you can see tab like window as container which seems like kind of webui.html tab-div

Just wondering what would be the cause?

**Comment by samuelmaddock** [comment]
I'm not familiar with how the Assima Train extension works, but by the looks of it, it's a cobrowsing solution.

In your example, you call `extensions.addTab(browserWindow.webContents, browserWindow)` which will register the https://google.com WebContents as the single tab of your application. This is being reflected by the Assima viewer(?) which seems to recreate Chrome's tabs UI.

Assima must be assuming the Electron app is actually Chrome which is why it's showing the tabs UI. This is not an issue with `electron-chrome-extensions`. Assima will need to update their code to detect if it's synced with an Electron app.

**Comment by Jenifer-TheCoder** [comment]
Oh then may i have to check with them, just wondering how the UI tab' DIV is pretty much similar to the one with newtab.html inside ui folder.
