### ISSUE TITLE
`modulePath` is not fully customizable (electron-chrome-extensions)

### ISSUE THREAD

**Issue by mingy98** [samuelmaddock/electron-browser-shell#40]
In `browser/index.ts`, the path of `preload.js` is `path.join(this.modulePath, "dist/preload.js")`. This means that developers only control `preload.js` if it is in a folder called `dist` and presents a problem when I `yarn add electron-chrome-extensions` and `__dirname` thinks that `__dirname` is the root directory of my project instead of the directory of the `electron-chrome-extensions` node module.

The fix would be to just have the path of `preload.js` be the `modulePath` option--remove the `dist/preload.js` and let users specify it themselves.

**Comment by samuelmaddock** [comment]
`dist/preload.js` is referring to a preload script included with the `electron-chrome-extensions` files.

It should be present in `<project-root>/node_modules/electron-chrome-extensions/dist/preload.js`

Are you moving preload.js outside of the electron-chrome-extensions directory? You should be able to specify
```ts
const chromeExtensions = new ElectronChromeExtensions({
  modulePath: require('path').join(__dirname, 'node_modules/electron-chrome-extensions')
})
```
