### ISSUE TITLE
feat: Implement URL pattern matching in tabs.query API

### ISSUE THREAD

**Issue by Pranav2612000** [samuelmaddock/electron-browser-shell#42]
Thank you for the amazing package. It saved me by allowing to use the officially unsupported browser APIs.

An improvement I needed to do was to implement URL pattern matching. I browsed through the index.js in the built package and found this snippet - which I then updated - to implement pattern matching.
```
if (isSet(info.url) && info.url !== tab.url) return false; // TODO: match URL pattern
```

If it still hasn't been implemented, I'll like to help with the implementation. But I'll need your help with how things are to be structured and the preferred way of implementing URL pattern matching ( The way I've done it is more focussed on the way I needed it)

**Comment by samuelmaddock** [comment]
Hi @Pranav2612000. You're welcome to fork this repository and submit a pull request with your changes.

If you do, it'd be great if the functionality could have a test written to confirm that the changes work.
https://github.com/samuelmaddock/electron-browser-shell/blob/c47bcb3c7a1ff274b469ecffb25245cf580e5811/packages/electron-chrome-extensions/spec/chrome-tabs-spec.ts#L39-L66

**Comment by samuelmaddock** [comment]
An existing pattern matching utility is already in the codebase which could be reused for this case. https://github.com/samuelmaddock/electron-browser-shell/blob/c47bcb3c7a1ff274b469ecffb25245cf580e5811/packages/electron-chrome-extensions/src/browser/api/common.ts#L106-L113

**Comment by Pranav2612000** [comment]
Sure. Thank you. Just a couple of follow up questions

1. I'll just use the matchesPattern function for the comparison. Right?

2. A sample test case to get started can be -    ` *:*.google.com/*` should match `https://www.google.com/helloworld` . Should it also match `https://google.com/helloworld` ?

**Comment by samuelmaddock** [comment]
> 1. I'll just use the matchesPattern function for the comparison. Right?

Yes, that should work.

> 2. A sample test case to get started can be -    ` *:*.google.com/*` should match `https://www.google.com/helloworld` . Should it also match `https://google.com/helloworld` ?

https://developer.chrome.com/docs/extensions/mv3/match_patterns/ includes the syntax and a list of example patterns. I don't think ` *:*.google.com/*` is a valid pattern according to `<url-pattern> := <scheme>://<host><path>`. It would need to be `*://*.google.com/*` based on my understanding.

**Comment by Pranav2612000** [comment]
Yes. Thank you. 
> I don't think *:*.google.com/* is a valid pattern according to <url-pattern> := <scheme>://<host><path>

Yeah. It isn't. My bad. Forgot the slashes.But yes, I'll use the examples in the documentation.

Thank you for the help. PR coming up in a couple of days. 😄

**Comment by Pranav2612000** [comment]
I tried to build the extensions using `npm run build:extensions` (with webpack 4) and then ran `npm run test:extensions`.

I am getting the following output
![image](https://user-images.githubusercontent.com/20909078/138127789-57872ce4-1ab3-4161-ac02-38251dceae1e.png)
 
 I don't think this is the expected output. Am I missing some critical step, to get the tests to run?

**Comment by samuelmaddock** [comment]
Added in 6b6977ec161e8eb4130583b7acb36929c69a90b4
