### ISSUE TITLE
Embedding Chrome App.

### ISSUE THREAD

**Issue by Alex313031** [samuelmaddock/electron-browser-shell#55]
@samuelmaddock Hello, I'm working on a Chromium fork for Linux, Windows, and MacOS. > https://thorium.rocks/ & https://github.com/Alex313031/Thorium/releases

I'm also working on a fork of Cog > https://github.com/Alex313031/cog-chromium However, as you may know, Chromium is deprecating Chrome Apps soon, and this app relies on API's that Manifest V3 extensions don't have. So I would like to package it as its own standalone app. Similar to atom or etcher. I did some quick googling on how one could embed a chrome app using electron or chromium embedded framework, and came across this.

Do you have any idea how I would go about this, or how I could use this or one of its subprojects to make it where a user just runs it, and Cog just shows by itself, as if it were a native app.

**Comment by samuelmaddock** [comment]
Manifest V3 support is currently limited in this project by #38. Additionally, I don't have plans to support the full, deprecated Chrome Apps API. For that I might recommend taking a look at nw.js which supports those APIs out of the box: https://docs.nwjs.io/en/latest/References/Chrome%20Extension%20APIs/
