### ISSUE TITLE
[electron-chrome-extensions] createTab can receive relative URLs

### ISSUE THREAD

**Issue by Kilian** [samuelmaddock/electron-browser-shell#73]
Some extensions, like [simple translate](https://chrome.google.com/webstore/detail/simple-translate/ibplnjkanclpjokhdolnendpplpjiace?hl=en), open their settings panel from inside the popup with a relative URL (`../options/...etc`).

This URL gets sent to the `createTab` function unchanged, while in regular Chrome it's made absolute by creating a new url similar to this: `url = new URL(recievedURL, poupLocationHref).href`, which should make it a fully qualified chrome-extension:// url as well. 

I tried looking for where new windows/tabs coming from the popup are handled but I couldn't find it. If you point me in the right direction I'm happy to make a PR.

**Comment by kauri-hero** [comment]
It's quite coincidental you are looking into this also, as we are troubleshooting this as well in our implementation, utilizing the `electron-chrome-extensions` package!
(overall it is amazing - thanks @samuelmaddock for all this work put in!)

We will look into your adjustments @Kilian as we also have faced several extensions (which are still on manifest v2), which aren't loading relative paths from the popup browser action including their extension id.

Will report back if we discover other aspects that can assist with this

**Comment by Kilian** [comment]
I published https://www.npmjs.com/package/@polypane/electron-chrome-extensions with the fix if you want to try it out.
