### ISSUE TITLE
[electron-chrome-extensions] context menu items are not grouped

### ISSUE THREAD

**Issue by Kilian** [samuelmaddock/electron-browser-shell#77]
In Chrome, when an extension exposes multiple context menu items, they get grouped under a menu with the extension name (I think). If `extensions.getContextMenuItems` could be made to work similarly that would be nice.

**Comment by samuelmaddock** [comment]
Seems like they get grouped if there's more than one entry. Attaching an example:
![image](https://user-images.githubusercontent.com/1656324/212784096-62653147-073c-4a9d-9e50-d18a7af54be5.png)
