### ISSUE TITLE
[electron-chrome-extensions] Update browser-action-list after removing extension

### ISSUE THREAD

**Issue by Kilian** [samuelmaddock/electron-browser-shell#78]
After removing an extension from the session, browser-action-list isn't updated so the icon is still visible, but doesn't do anything.

Providing a mechanism to refresh browser-action-list (or having it do so automatically) would be nice.

**Comment by kauri-hero** [comment]
I'm so excited to see the recent activity on this repo @samuelmaddock @Kilian 

I'm organizing my thanks with some sponsorship
Would love to show you a demo of our electron browser we have built @samuelmaddock - I emailed you recently.

hope you all are well and looking forward to a great year in 2023!
