### ISSUE TITLE
[electron-chrome-extensions] when I tried to upgrade electron to version 25.0.1, error occured

### ISSUE THREAD

**Issue by pinkcao** [samuelmaddock/electron-browser-shell#88]
here's error message: 

TypeError: Cannot read properties of undefined (reading 'id')
    at WebNavigationAPI.onFinishLoad
    at EventEmitter.emit

seems the error is cause by the param "tab" undefined.
I'm not sure how to fix it, but here's my dependencies:
    "electron-chrome-context-menu": "^1.1.0",
    "electron-chrome-extensions": "^3.10.0"
    "electron": "^25.0.1",
    "electron-builder": "^23.6.0"  (this is meant for package the whole project to a release, won't matter anything)

**Comment by samuelmaddock** [comment]
Looks like a bug upstream in Electron https://github.com/electron/electron/issues/38566

**Comment by samuelmaddock** [comment]
Fixed in electron-chrome-extensions@3.10.1

**Comment by pinkcao** [comment]
thanks for solving it, it works.
