### ISSUE TITLE
npm start Fails Due to Missing electron-chrome-web-store Package

### ISSUE THREAD

**Issue by syedwastil** [samuelmaddock/electron-browser-shell#99]
**Description of the bug**
When attempting to run `yarn start` after cloning the repository, the process fails with an error indicating that the `electron-chrome-web-store` package is not found.

**To Reproduce**
1. Clone the repository:
 ```bash 
git clone git@github.com:samuelmaddock/electron-browser-shell.git
cd electron-browser-shell

```
2. Install dependencies using yarn:
```bash
yarn
```
3. Start the application:
```bash
yarn start
```
4. Observe the error related to `electron-chrome-web-store`.
![image](https://github.com/user-attachments/assets/18476c10-e2e1-417e-914b-ad2a99b4fb9d)

**Expected behavior**
The application should start without requiring additional build steps as suggested in Readme .

**Workaround**
Running `yarn build` followed by `yarn start` successfully starts the application.

**Comment by samuelmaddock** [comment]
Sorry about that, this was an issue because I never downloaded the package from npm while testing locally.

https://github.com/samuelmaddock/electron-browser-shell/blob/808b120e089089a60e98b90ca7f0d1c352284ca7/packages/shell/package.json#L18

Fixed in 753ad24f980ebf8c10c330e93fc6d5a93ced2eab
